```{r echo=FALSE, message=FALSE, warning=FALSE}
library(lme4)
library(tidyverse)
library(dplyr)
library(MASS)
library(readr)
library(ggplot2)
library(effectsize)
library(tidyr)
library("emmeans")  # emmeans must now be loaded explicitly for follow-up tests.
library("afex")     # needed for ANOVA functions.
library("multcomp")
library(MASS) # v7.3-50
library(apaTables) # ic
library (esc)
library(reshape2)
library(data.table)
library(readxl)
library(ggrepel)
library(ggpubr)
```







```{r}


set1 <- read_excel("D:/OneDrive/EladsB/CognitiveNeuroscience/nachshon/Experiment_2/Data_Analysis/sub_set1.xlsx")
set2 <- read_excel("D:/OneDrive/EladsB/CognitiveNeuroscience/nachshon/Experiment_2/Data_Analysis/sub_set2.xlsx")
set3 <- read_excel("D:/OneDrive/EladsB/CognitiveNeuroscience/nachshon/Experiment_2/Data_Analysis/sub_set3.xlsx")
set4 <- read_excel("D:/OneDrive/EladsB/CognitiveNeuroscience/nachshon/Experiment_2/Data_Analysis/sub_set4.xlsx")
set5 <- read_excel("D:/OneDrive/EladsB/CognitiveNeuroscience/nachshon/Experiment_2/Data_Analysis/sub_set5.xlsx")
set6 <- read_excel("D:/OneDrive/EladsB/CognitiveNeuroscience/nachshon/Experiment_2/Data_Analysis/sub_set6.xlsx")
set7 <- read_excel("D:/OneDrive/EladsB/CognitiveNeuroscience/nachshon/Experiment_2/Data_Analysis/sub_set7.xlsx")
set8 <- read_excel("D:/OneDrive/EladsB/CognitiveNeuroscience/nachshon/Experiment_2/Data_Analysis/sub_set8.xlsx")


#Important Variabels

#vis_corr_resp - the correct response key.
#visual_stim - the name of the visual stimulus presented.
#response_viz_rep_keys - subject response to the visual stim.




all_data <- rbind(set1,set2,set3,set4,set5,set6,set7,set8)



all_data$participant <- rep(1:70,each = 240)

all_data <- all_data[c('response_emo_resp_keys','correct_emo_resp_keys','response_time_emo_resp_keys','visualhint','vis_corr_resp','visual_stim','correct_vis_resp_keys','response_vis_resp_keys','response_time_vis_resp_keys','emotion','participant','emo_stim_name')]

all_data <- na.omit(all_data)

for (i in 1:nrow(all_data)) {
  if (grepl('p',all_data$emo_stim_name[i]) & all_data$response_emo_resp_keys[i] == 'p'){ #If positive stim - pressed 'P'
    all_data$correct_emo_resp_keys[i] <- 1
  } else if (grepl('p',all_data$emo_stim_name[i]) & all_data$response_emo_resp_keys[i] == 'q') {#if positive stim - pressed Q
    all_data$correct_emo_resp_keys[i] <- 0
  } else if (grepl('n',all_data$emo_stim_name[i]) & all_data$response_emo_resp_keys[i] == 'q') {#if negative stim - pressed 'Q'
    all_data$correct_emo_resp_keys[i] <- 1
  } else if (grepl('n',all_data$emo_stim_name[i]) & all_data$response_emo_resp_keys[i] == 'p') { #if negative stim - pressed 'P'
    all_data$correct_emo_resp_keys[i] <- 0
  }
}


all_data <- na.omit(all_data)


############### Data Pre-processing ###############
# 1) Finding participants that responded in the opposite (supposed) evoked emotion:
all_data <- subset(all_data, participant != 29 & participant != 42 & participant != 68 & participant != 52 & participant != 35 & participant != 59)
                   




#2) Finding pictures whos average error responses is higher then 50%:

all_data <- subset(all_data, emo_stim_name != 'p_94' & emo_stim_name != 'p_42' & emo_stim_name != 'p_108' & emo_stim_name != 'p_12' & emo_stim_name != 'p_21' & emo_stim_name != 'p_79' & emo_stim_name != 'p_39' & emo_stim_name != 'p_22' & emo_stim_name != 'p_80' & emo_stim_name != 'p_6') #10 pictures.




# 3) Examining the RT density function:
ggplot(all_data,aes(x=response_time_emo_resp_keys)) + geom_density() + ggtitle('Before Triming') 
# Need to trim 0.005 of trials with slow RT


# Trimming overall outlier responses.
all_data_new <- subset(all_data,response_time_emo_resp_keys <= 6150 & response_time_emo_resp_keys >= 200)
1 - nrow(all_data_new)/nrow(all_data)
all_data <- all_data_new


# Trimming outlier responses for each participant by each condition.
all_data <- all_data  %>% group_by(participant,emotion,visualhint) %>% 
  mutate(rt_z_score = scale(response_time_emo_resp_keys))
all_data <- subset(all_data,rt_z_score < 3.5 & rt_z_score > -3.5)



#all_data %>% group_by(visualhint) %>% summarize(mean(correct_vis_resp_keys))




# Classifying is target was 'present' or 'absent'.
all_data$present <- ifelse(grepl('present',all_data$visual_stim) == TRUE, 'present','absent')


# PE of Visual Task.
all_data$visual_pe <- ifelse(tolower(all_data$vis_corr_resp) == tolower(all_data$response_vis_resp_keys),0,1)


# PE of Emotional Task.
all_data$error_resp <- ifelse(all_data$correct_emo_resp_keys == 1,0,1)



# Categorizing as 'Easy' or 'Hard' search task.
all_data$visualhint <-ifelse(all_data$visualhint == 'fs_shape_h' | all_data$visualhint == 'fs_color_h', 'easy','hard')



# Presenting simplified stimulus name.
all_data$visual_stim <- ifelse(grepl('FSC',all_data$visual_stim) == TRUE, 'Color Search',
                               ifelse(grepl('FSS',all_data$visual_stim) == TRUE, 'Shape Search','Conjunction Search'))
 










all_data$visualhint <- as.factor(all_data$visualhint)
all_data$emotion <- as.factor(all_data$emotion)

## RT Analysis of the emotional pictures. 
aov_rt <- aov_ez("participant", "response_time_emo_resp_keys", all_data,
                 within = c("visualhint", "emotion"),anova_table=list(correction = "GG", es = "pes"))
knitr::kable((nice(aov_rt)))


afex_plot(aov_rt,x = "visualhint",trace ="emotion",
          error_arg = list(size = 0.8, width = 0.2),
          point_arg = list(size = 2), line_arg = list(size = 0.9),data_alpha = 0,
          error_ci = TRUE) +
  theme_classic() + ylim(c(0,3500)) + ggtitle("Reaction time") + ylab("RT")







## Accuracy Analysis of emotional pictures.
aov_error <- aov_ez("participant", "error_resp", all_data,
                 within = c("visualhint", "emotion"),anova_table=list(correction = "GG", es = "pes"))
knitr::kable((nice(aov_error)))



afex_plot(aov_error,x = "emotion", trace = 'visualhint',
          error_arg = list(size = 0.8, width = 0.2),
          point_arg = list(size = 2), line_arg = list(size = 0.9),data_alpha = 0,
          error_ci = TRUE) +
  theme_classic() + ggtitle("Error Emotional Task task")


```






```{r}


## RT Analysis of Vs_cue.
aov_vsrt <- aov_ez("participant", "response_time_vis_resp_keys", all_data,
                 within = c("visual_stim"),anova_table=list(correction = "GG", es = "pes"))
knitr::kable((nice(aov_vsrt)))



afex_plot(aov_vsrt,x = "visual_stim",#,trace ="emotion",
          error_arg = list(size = 0.8, width = 0.2),
          point_arg = list(size = 2), line_arg = list(size = 0.9),data_alpha = 0,
          error_ci = TRUE) +
  theme_classic() + ggtitle("Reaction time visual task")











### Accuracy Analysis of VS_Cue.
aov_vspe <- aov_ez("participant", "error_resp", all_data,
                  within = c("visual_stim"),anova_table=list(correction = "GG", es = "pes"))
knitr::kable((nice(aov_vspe)))



afex_plot(aov_vspe,x = "visual_stim",#, trace = 'visual_stim',
          error_arg = list(size = 0.8, width = 0.2),
          point_arg = list(size = 2), line_arg = list(size = 0.9),data_alpha = 0,
          error_ci = TRUE) +
  theme_classic() + ggtitle("Accuracy Visual task")






# Exporting the data:
#write.csv(aov_vsrt[["data"]][["wide"]],'D:/OneDrive/EladsB/CognitiveNeuroscience/nachshon/Experiment_2/Data_Analysis/VS_RT.csv')

#write.csv(aov_vspe[["data"]][["wide"]],'D:/OneDrive/EladsB/CognitiveNeuroscience/nachshon/Experiment_2/Data_Analysis/VS_PE.csv')


```











PE Analysis by 'target present' | 'target absent'

```{r} 

## Should I split the analysis for visual_hint_present and visual_hint_not_present???? ###





# Target Present Analysis
data_present <- subset(all_data, present == 'present')



aov_vs_present_pe <- aov_ez("participant", "error_resp", data_present,
                  within = c("visual_stim"),anova_table=list(correction = "GG", es = "pes"))
knitr::kable((nice(aov_vs_present_pe)))





afex_plot(aov_vs_present_pe,x = "visual_stim", 
          error_arg = list(size = 0.8, width = 0.2),
          point_arg = list(size = 2), line_arg = list(size = 0.9),data_alpha = 0,
          error_ci = TRUE) +
  theme_classic() + ggtitle("Percentage Error")











# Target Absent Analysis

data_absent <- subset(all_data, present == 'absent')




aov_vs_absent_pe <- aov_ez("participant", "error_resp", data_absent,
                  within = c("visual_stim"),anova_table=list(correction = "GG", es = "pes"))
knitr::kable((nice(aov_vs_absent_pe)))




afex_plot(aov_vs_absent_pe,x = "visual_stim", 
          error_arg = list(size = 0.8, width = 0.2),
          point_arg = list(size = 2), line_arg = list(size = 0.9),data_alpha = 0,
          error_ci = TRUE) +
  theme_classic() + ggtitle("Percentage Error")

```





Emotional Stimuli Analysis themselfs
```{r}
library(hrbrthemes)
emo_stim <- read_excel("D:/OneDrive/EladsB/CognitiveNeuroscience/nachshon/Experiment_2/emo_stim/Emo_Stim_Data.xlsx")
emo_stim <- emo_stim %>% dplyr::rename(emo_stim_name = stimulus_name)


emo_stim %>% group_by(emotion) %>% summarise(count = n(),
                                             mean = mean(emotion_valence),
                                             sd = sd(emotion_valence),
                                             median = median(emotion_valence))

emo_pos <- subset(emo_stim,emotion == 'p')

emo_neg <- subset(emo_stim,emotion == 'n')


gghistogram(emo_stim, x = 'emotion_valence',color = "emotion", fill = "emotion", bins = 60, add = "median", rug = TRUE,
   palette = c("red", "#00AFBB"), alpha = 0.2)  + scale_x_continuous(seq(1,8,1)) + ggtitle("Before Trimming")






# The naps ratings were on a scale of:
#     1      2      3      4      5      6     7      8       9
#    very                                                   very
#   negative                                               positive

```





